#pragma once
#include "../XSolace/Lib/Formatter.h"
#include "../XSolace/Lib/Log.h"
#include "../XSolace/Lib/Memory.h"
#include "../XSolace/Lib/SMC.h"
#include "../XSolace/Lib/XAM.h"


#include "../XSolace/Games/Crackdown.h"
#include "../XSolace/Games/CSGO.h"
#include "../XSolace/Games/Dashboard.h"
#include "../XSolace/Games/DeadRising2.h"
#include "../XSolace/Games/EnemyTerritory.h"
#include "../XSolace/Games/SaintsRow.h"
#include "../XSolace/Games/SaintsRow2.h"
#include "../XSolace/Games/SaintsRow3.h"
#include "../XSolace/Games/SaintsRowGOH.h"
#include "../XSolace/Games/SleepingDogs.h"
#include "../XSolace/Games/SonicAdventure.h"
#include "../XSolace/Games/TheClub.h"
